# Common configuration
AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2
  Exclude:
    - 'db/schema.rb'

Rails:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/*'
